# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -id {Project 1-19}  -string {{CRITICAL WARNING: [Project 1-19] Could not find the file 'U:/basys3_master/Basys3_Master.xdc'.}}  -suppress 
set_msg_config  -id {Labtools 27-1429}  -string {{ERROR: [Labtools 27-1429] XML parser encountered a problem in file C:/Users/Eric/Desktop/NEW/NEW.hw/hw_1/hw.xml at line 3 : Bad end of element}}  -suppress 

create_project -in_memory -part xc7a35tcpg236-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Ben/Desktop/FINALPROJECTFSM/FINALPROJECTFSM.cache/wt [current_project]
set_property parent.project_path C:/Users/Ben/Desktop/FINALPROJECTFSM/FINALPROJECTFSM.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Ben/Desktop/FINALPROJECTFSM/FINALPROJECTFSM.srcs/sources_1/new/SSEG.vhd
  C:/Users/Ben/Desktop/FINALPROJECTFSM/FINALPROJECTFSM.srcs/sources_1/new/Source.vhd
}
read_xdc C:/Users/Ben/Desktop/FINALPROJECTFSM/FINALPROJECTFSM.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Ben/Desktop/FINALPROJECTFSM/FINALPROJECTFSM.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]

catch { write_hwdef -file Source.hwdef }
synth_design -top Source -part xc7a35tcpg236-1
write_checkpoint -noxdef Source.dcp
catch { report_utilization -file Source_utilization_synth.rpt -pb Source_utilization_synth.pb }
